// This file contains mock evaluation results for the UTBK simulation
// In a real app, these would be generated by the ChatGPT API

export const mockEvaluations = {
  totalScore: 112,
  subtests: {
    "Penalaran Umum": {
      score: 24,
      total: 30,
    },
    "Pengetahuan dan Pemahaman Umum": {
      score: 15,
      total: 20,
    },
    "Kemampuan Memahami Bacaan dan Menulis": {
      score: 14,
      total: 20,
    },
    "Pengetahuan Kuantitatif": {
      score: 16,
      total: 20,
    },
    "Literasi dalam Bahasa Indonesia": {
      score: 21,
      total: 30,
    },
    "Literasi dalam Bahasa Inggris": {
      score: 15,
      total: 20,
    },
    "Penalaran Matematika": {
      score: 12,
      total: 20,
    },
  },
  questions: [
    {
      id: 1,
      text: "Jika semua A adalah B, dan beberapa B adalah C, maka...",
      options: [
        { id: "A", text: "Semua A adalah C" },
        { id: "B", text: "Beberapa A adalah C" },
        { id: "C", text: "Semua C adalah A" },
        { id: "D", text: "Tidak dapat ditentukan hubungan antara A dan C" },
      ],
      userAnswer: "B",
      correctAnswer: "D",
      correct: false,
      explanation:
        "Dari premis yang diberikan, kita tidak dapat menyimpulkan hubungan pasti antara A dan C. Meskipun semua A adalah B, dan beberapa B adalah C, kita tidak tahu apakah ada irisan antara himpunan A dan himpunan C. Bisa saja semua A berada di luar himpunan B yang merupakan C, atau bisa juga beberapa A adalah C.",
    },
    {
      id: 2,
      text: "Perhatikan pola berikut: 3, 6, 11, 18, 27, ... Angka berikutnya dalam pola tersebut adalah...",
      options: [
        { id: "A", text: "36" },
        { id: "B", text: "38" },
        { id: "C", text: "40" },
        { id: "D", text: "42" },
      ],
      userAnswer: "B",
      correctAnswer: "B",
      correct: true,
      explanation:
        "Pola selisih antara angka berturut-turut adalah 3, 5, 7, 9, ... yang membentuk barisan aritmatika dengan beda 2. Selisih berikutnya adalah 9 + 2 = 11, sehingga angka berikutnya adalah 27 + 11 = 38.",
    },
    {
      id: 3,
      text: "Protokol Kyoto berkaitan dengan masalah global apa?",
      options: [
        { id: "A", text: "Perdagangan internasional" },
        { id: "B", text: "Perubahan iklim" },
        { id: "C", text: "Hak asasi manusia" },
        { id: "D", text: "Perlindungan keanekaragaman hayati" },
      ],
      userAnswer: "B",
      correctAnswer: "B",
      correct: true,
      explanation:
        "Protokol Kyoto adalah perjanjian internasional yang terkait dengan Konvensi Kerangka Kerja PBB tentang Perubahan Iklim (UNFCCC). Protokol ini menetapkan target pengurangan emisi gas rumah kaca yang mengikat secara hukum bagi negara-negara industri.",
    },
    {
      id: 4,
      text: "Jika 3x + 2y = 12 dan 2x - y = 5, maka nilai dari x + y adalah...",
      options: [
        { id: "A", text: "3" },
        { id: "B", text: "4" },
        { id: "C", text: "5" },
        { id: "D", text: "6" },
      ],
      userAnswer: "C",
      correctAnswer: "C",
      correct: true,
      explanation:
        "Dari persamaan 2x - y = 5, kita peroleh y = 2x - 5. Substitusi ke persamaan 3x + 2y = 12 menghasilkan 3x + 2(2x - 5) = 12. Sederhanakan: 3x + 4x - 10 = 12, sehingga 7x = 22, x = 22/7. Substitusi nilai x ke y = 2x - 5 menghasilkan y = 2(22/7) - 5 = 44/7 - 5 = 44/7 - 35/7 = 9/7. Jadi x + y = 22/7 + 9/7 = 31/7 = 4 3/7 ≈ 5.",
    },
    {
      id: 5,
      text: 'Bacalah kutipan berikut:\n\n"Pendidikan adalah senjata paling mematikan di dunia, karena dengan pendidikan, Anda dapat mengubah dunia." - Nelson Mandela\n\nMakna kutipan tersebut adalah...',
      options: [
        { id: "A", text: "Pendidikan dapat digunakan sebagai alat untuk berperang" },
        { id: "B", text: "Pendidikan adalah hal yang berbahaya bagi dunia" },
        { id: "C", text: "Pendidikan memiliki kekuatan besar untuk membawa perubahan positif di dunia" },
        { id: "D", text: "Pendidikan hanya berguna bagi orang-orang tertentu" },
      ],
      userAnswer: "C",
      correctAnswer: "C",
      correct: true,
      explanation:
        "Kutipan tersebut menggunakan metafora 'senjata paling mematikan' untuk menggambarkan kekuatan besar yang dimiliki pendidikan. Nelson Mandela menekankan bahwa pendidikan memiliki kekuatan transformatif yang dapat mengubah dunia menjadi lebih baik, bukan dalam arti harfiah sebagai alat perang atau sesuatu yang berbahaya.",
    },
  ],
}
