// Built-in questions for Literasi dalam Bahasa Indonesia subtest

export const literasiBahasaIndonesiaQuestions = [
  {
    id: 1,
    text: "Bacalah teks berikut dengan cermat!\n\nLaporan Global Gender Gap Report 2023 yang dirilis World Economic Forum (WEF) menunjukkan adanya penurunan partisipasi perempuan dalam perekonomian Indonesia dari peringkat 80 pada 2022 menjadi 87 pada tahun lalu. Laporan tersebut juga menunjukkan bahwa indeks kesenjangan gender di Indonesia berada di poin 0,697–angka ini stagnan paling tidak selama empat tahun terakhir.\n\nSementara, Survei Angkatan Kerja Nasional dari BPS menunjukkan rata-rata upah perempuan masih lebih rendah dibandingkan laki-laki. Tak hanya itu, riset juga memperlihatkan kurangnya akses ke peluang karier yang setara dan diskriminasi gender, khususnya bagi para ibu.\n\nPeluang partisipasi perempuan perlu dilihat dari sisi supply (pasokan) dan demand (permintaan). Dari sisi pasokan, perempuan masih terjebak dalam norma tradisional yang membatasi pilihan karier dan kesempatan meningkatkan keterampilan mereka, seperti akses pekerjaan dalam bidang rekayasa dan teknologi. Sedangkan, dari sisi permintaan, perempuan masih mengalami diskriminasi gaji dan beban ganda mengurus rumah tangga.\n\nDalam ruang kerja yang bersifat informal, 60% perempuan sebetulnya mendominasi porsi penggiat UMKM di Indonesia. Sayangnya, mereka masih menemui perlakuan berbeda untuk memulai bisnis, seperti kendala sosial budaya, keterbatasan akses pelatihan dan sumber daya finansial, dan diskriminasi dalam pengambilan keputusan bisnis. Hal ini membatasi aspirasi dan potensi mereka.\n\nPernyataan yang tepat mengenai survei angkatan kerja nasional dari BPS adalah....",
    type: "single",
    options: [
      { id: "A", text: "Akses peluang karier lebih banyak untuk perempuan." },
      { id: "B", text: "Perempuan memiliki tunjangan dan gaji yang lebih besar." },
      { id: "C", text: "Para ibu memiliki peluang yang sama dalam mengejar karier." },
      { id: "D", text: "Jumlah pekerja perempuan lebih tinggi dibandingkan laki-laki." },
      { id: "E", text: "Laki-laki memiliki upah yang lebih tinggi dibandingkan perempuan." },
    ],
    correctAnswer: "E",
    explanation: "Berdasarkan teks, Survei Angkatan Kerja Nasional dari BPS menunjukkan bahwa 'rata-rata upah perempuan masih lebih rendah dibandingkan laki-laki'. Ini berarti laki-laki memiliki upah yang lebih tinggi dibandingkan perempuan.",
  },
  {
    id: 2,
    text: "Bacalah teks berikut dengan cermat!\n\nLaporan Global Gender Gap Report 2023 yang dirilis World Economic Forum (WEF) menunjukkan adanya penurunan partisipasi perempuan dalam perekonomian Indonesia dari peringkat 80 pada 2022 menjadi 87 pada tahun lalu. Laporan tersebut juga menunjukkan bahwa indeks kesenjangan gender di Indonesia berada di poin 0,697–angka ini stagnan paling tidak selama empat tahun terakhir.\n\nSementara, Survei Angkatan Kerja Nasional dari BPS menunjukkan rata-rata upah perempuan masih lebih rendah dibandingkan laki-laki. Tak hanya itu, riset juga memperlihatkan kurangnya akses ke peluang karier yang setara dan diskriminasi gender, khususnya bagi para ibu.\n\nPeluang partisipasi perempuan perlu dilihat dari sisi supply (pasokan) dan demand (permintaan). Dari sisi pasokan, perempuan masih terjebak dalam norma tradisional yang membatasi pilihan karier dan kesempatan meningkatkan keterampilan mereka, seperti akses pekerjaan dalam bidang rekayasa dan teknologi. Sedangkan, dari sisi permintaan, perempuan masih mengalami diskriminasi gaji dan beban ganda mengurus rumah tangga.\n\nDalam ruang kerja yang bersifat informal, 60% perempuan sebetulnya mendominasi porsi penggiat UMKM di Indonesia. Sayangnya, mereka masih menemui perlakuan berbeda untuk memulai bisnis, seperti kendala sosial budaya, keterbatasan akses pelatihan dan sumber daya finansial, dan diskriminasi dalam pengambilan keputusan bisnis. Hal ini membatasi aspirasi dan potensi mereka.\n\n\n\n\n\n\n\nBerdasarkan teks di atas dapat disimpulkan bahwa perempuan mempunyai banyak tantangan untuk mencapai kemandirian secara finansial. Salah satu tantangannya adalah....",
    type: "single",
    options: [
      { id: "A", text: "Tingkat pendidikan yang rendah" },
      { id: "B", text: "Mempunyai beban ganda sekaligus" },
      { id: "C", text: "Porsi ruang UMKM didominasi oleh laki-laki" },
      { id: "D", text: "Tidak adanya peluang karier untuk perempuan" },
      { id: "E", text: "Tidak memiliki keterampilan dalam bidang teknologi" },
    ],
    correctAnswer: "B",
    explanation: "Berdasarkan teks, salah satu tantangan perempuan adalah 'beban ganda mengurus rumah tangga' yang disebutkan pada paragraf ketiga. Ini menunjukkan bahwa perempuan harus menjalankan peran ganda sebagai pekerja dan pengurus rumah tangga.",
  },
  {
    id: 3,
    text: "Jika pelaku UMKM perempuan memiliki akses pelatihan dan sumber daya finansial yang mumpuni, kemungkinan yang akan terjadi adalah....",
    type: "single",
    options: [
      { id: "A", text: "Potensi mereka dalam mengembangkan bisnis akan optimal." },
      { id: "B", text: "Aspirasi mereka sebagai pelaku UMKM akan semakin rendah." },
      { id: "C", text: "Perempuan akan mendominasi perannya sebagai pelaku UMKM." },
      { id: "D", text: "Pelaku UMKM perempuan akan semakin banyak dan berkembang." },
      { id: "E", text: "Perempuan mendapatkan diskriminasi dalam mengembangkan bisnis." },
    ],
    correctAnswer: "A",
    explanation: "Berdasarkan teks, perempuan pelaku UMKM menghadapi 'keterbatasan akses pelatihan dan sumber daya finansial' yang membatasi aspirasi dan potensi mereka. Jika keterbatasan ini diatasi, maka potensi mereka dalam mengembangkan bisnis akan optimal.",
  },
  {
    id: 4,
    text: "Bacalah teks berikut dengan cermat!\n\nPertusis adalah penyakit batuk rejan akibat infeksi bakteri Bordetella pertussis. Orang yang terkena penyakit ini akan mengalami gejala batuk yang kuat dan terus menerus disertai \"mengi\" karena pasien berupaya keras menarik napas. Pada akhirnya, orang tersebut batuk disertai dengan bunyi yang khas. Selain itu, pasien juga biasanya mengalami demam ringan, pilek dan hidung tersumbat, mata merah dan berair hingga bersin-bersin serta mengalami muntah-muntah saat atau setelah batuk.\n\nPertusis menular melalui kontak langsung. Satu orang yang terinfeksi dapat menimbulkan 17 kasus pertusis baru di populasi yang tidak diimunisasi. Hampir 75% kasus pertusis pada bayi terjadi akibat kontak di lingkungan keluarga. Pertusis dapat menyerang semua golongan umur. Bagi bayi yang terkena penyakit ini, 1 dari 10 di antaranya menderita pneumonia atau radang paru-paru. Sementara, kasus meninggal dunia terjadi pada 1 dari 100 pasien pertusis.\n\nStrategi imunisasi di awal kehidupan ternyata berperan penting dalam mencegah serta mengurangi angka kesakitan dan kematian akibat pertusis di Indonesia, terutama pada bayi. Untuk mencegah pertusis mewabah, Indonesia juga perlu memperluas sistem deteksi pemeriksaan laboratorium yang memadai di setiap daerah untuk menyokong pemantauan dan identifikasi kasus. Sayangnya, informasi penyebaran pertusis masih tergolong senyap karena bisa jadi tidak terdeteksi dengan baik.\n\nTabel riwayat pemeriksaan seorang pasien\nTahap | Gejala\n--- | ---\n1 (1 minggu pertama) | Hidung berair atau tersumbat\nDemam ringan\nBatuk ringan dan sesekali\nApnea (jeda pernapasan yang mengancam jiwa) dan sianosis (berubah menjadi biru atau ungu) pada bayi dan anak kecil\n2 (Setelah 1 minggu) | Mengeluarkan suara seperti \"teriakan\" bernada tinggi ketika mereka akhirnya bisa menarik napas setelah batuknya berakhir\nMuntah saat atau setelah batuk\nKesulitan bernapas\n\nBerdasarkan teks di atas, penyakit pertusis dapat dicegah dengan cara....",
    type: "single",
    image: "/images/questions/indotabel.jpg",
    options: [
      { id: "A", text: "Mengenali tanda dan gejala pertusis" },
      { id: "B", text: "Melakukan imunisasi lengkap saat bayi" },
      { id: "C", text: "Melakukan tes kesehatan satu tahun sekali" },
      { id: "D", text: "Menghindari kontak langsung dengan penderita" },
      { id: "E", text: "Memantau perkembangan sejak dalam kandungan" },
    ],
    correctAnswer: "B",
    explanation: "Berdasarkan teks, 'Strategi imunisasi di awal kehidupan ternyata berperan penting dalam mencegah serta mengurangi angka kesakitan dan kematian akibat pertusis di Indonesia, terutama pada bayi.' Ini menunjukkan bahwa imunisasi lengkap saat bayi adalah cara yang efektif untuk mencegah penyakit pertusis.",
  },
  {
    id: 5,
    text: "Bacalah teks berikut dengan cermat!\n\nPertusis adalah penyakit batuk rejan akibat infeksi bakteri Bordetella pertussis. Orang yang terkena penyakit ini akan mengalami gejala batuk yang kuat dan terus menerus disertai \"mengi\" karena pasien berupaya keras menarik napas. Pada akhirnya, orang tersebut batuk disertai dengan bunyi yang khas. Selain itu, pasien juga biasanya mengalami demam ringan, pilek dan hidung tersumbat, mata merah dan berair hingga bersin-bersin serta mengalami muntah-muntah saat atau setelah batuk.\n\nPertusis menular melalui kontak langsung. Satu orang yang terinfeksi dapat menimbulkan 17 kasus pertusis baru di populasi yang tidak diimunisasi. Hampir 75% kasus pertusis pada bayi terjadi akibat kontak di lingkungan keluarga. Pertusis dapat menyerang semua golongan umur. Bagi bayi yang terkena penyakit ini, 1 dari 10 di antaranya menderita pneumonia atau radang paru-paru. Sementara, kasus meninggal dunia terjadi pada 1 dari 100 pasien pertusis.\n\nStrategi imunisasi di awal kehidupan ternyata berperan penting dalam mencegah serta mengurangi angka kesakitan dan kematian akibat pertusis di Indonesia, terutama pada bayi. Untuk mencegah pertusis mewabah, Indonesia juga perlu memperluas sistem deteksi pemeriksaan laboratorium yang memadai di setiap daerah untuk menyokong pemantauan dan identifikasi kasus. Sayangnya, informasi penyebaran pertusis masih tergolong senyap karena bisa jadi tidak terdeteksi dengan baik.\n\nTabel riwayat pemeriksaan seorang pasien\nTahap | Gejala\n--- | ---\n1 (1 minggu pertama) | Hidung berair atau tersumbat\nDemam ringan\nBatuk ringan dan sesekali\nApnea (jeda pernapasan yang mengancam jiwa) dan sianosis (berubah menjadi biru atau ungu) pada bayi dan anak kecil\n2 (Setelah 1 minggu) | Mengeluarkan suara seperti \"teriakan\" bernada tinggi ketika mereka akhirnya bisa menarik napas setelah batuknya berakhir\nMuntah saat atau setelah batuk\nKesulitan bernapas\n\n Berikut ini yang bukan gejala penyakit pertusis adalah....",
    type: "single",
    image: "/images/questions/indotabel.jpg",

    options: [
      { id: "A", text: "Pilek" },
      { id: "B", text: "Mata berair" },
      { id: "C", text: "Muntah-muntah" },
      { id: "D", text: "Perut kembung" },
      { id: "E", text: "Demam ringan" },
    ],
    correctAnswer: "D",
    explanation: "Berdasarkan teks, gejala pertusis meliputi batuk kuat dan terus menerus, mengi, demam ringan, pilek, hidung tersumbat, mata merah dan berair, bersin-bersin, dan muntah-muntah. Perut kembung tidak disebutkan sebagai gejala pertusis dalam teks.",
  },
  {
    id: 6,
    text: "Bacalah teks berikut dengan cermat!\n\nPertusis adalah penyakit batuk rejan akibat infeksi bakteri Bordetella pertussis. Orang yang terkena penyakit ini akan mengalami gejala batuk yang kuat dan terus menerus disertai \"mengi\" karena pasien berupaya keras menarik napas. Pada akhirnya, orang tersebut batuk disertai dengan bunyi yang khas. Selain itu, pasien juga biasanya mengalami demam ringan, pilek dan hidung tersumbat, mata merah dan berair hingga bersin-bersin serta mengalami muntah-muntah saat atau setelah batuk.\n\nPertusis menular melalui kontak langsung. Satu orang yang terinfeksi dapat menimbulkan 17 kasus pertusis baru di populasi yang tidak diimunisasi. Hampir 75% kasus pertusis pada bayi terjadi akibat kontak di lingkungan keluarga. Pertusis dapat menyerang semua golongan umur. Bagi bayi yang terkena penyakit ini, 1 dari 10 di antaranya menderita pneumonia atau radang paru-paru. Sementara, kasus meninggal dunia terjadi pada 1 dari 100 pasien pertusis.\n\nStrategi imunisasi di awal kehidupan ternyata berperan penting dalam mencegah serta mengurangi angka kesakitan dan kematian akibat pertusis di Indonesia, terutama pada bayi. Untuk mencegah pertusis mewabah, Indonesia juga perlu memperluas sistem deteksi pemeriksaan laboratorium yang memadai di setiap daerah untuk menyokong pemantauan dan identifikasi kasus. Sayangnya, informasi penyebaran pertusis masih tergolong senyap karena bisa jadi tidak terdeteksi dengan baik.\n\nTabel riwayat pemeriksaan seorang pasien\nTahap | Gejala\n--- | ---\n1 (1 minggu pertama) | Hidung berair atau tersumbat\nDemam ringan\nBatuk ringan dan sesekali\nApnea (jeda pernapasan yang mengancam jiwa) dan sianosis (berubah menjadi biru atau ungu) pada bayi dan anak kecil\n2 (Setelah 1 minggu) | Mengeluarkan suara seperti \"teriakan\" bernada tinggi ketika mereka akhirnya bisa menarik napas setelah batuknya berakhir\nMuntah saat atau setelah batuk\nKesulitan bernapas\n\n\n\n\n\nPernyataan yang sesuai dengan informasi pada paragraf kedua teks di atas adalah....",
    type: "single",
    options: [
      { id: "A", text: "Pertusis hanya menyerang bayi, anak-anak, dan remaja." },
      { id: "B", text: "Pertusis ditemukan pada orang dewasa penderita pneumonia." },
      { id: "C", text: "Populasi yang tidak diimunisasi lebih berisiko terkena pertusis." },
      { id: "D", text: "Kontak secara langsung tidak terlalu berisiko penyakit pertusis." },
      { id: "E", text: "Setengah dari 100 kasus pertusis berpontensi meninggal dunia." },
    ],
    correctAnswer: "C",
    explanation: "Berdasarkan teks, 'Satu orang yang terinfeksi dapat menimbulkan 17 kasus pertusis baru di populasi yang tidak diimunisasi.' Ini menunjukkan bahwa populasi yang tidak diimunisasi lebih berisiko terkena pertusis.",
  },
  {
    id: 7,
    text: "Pernyataan yang tepat mengenai tabel riwayat pemeriksaan pasien pada teks tersebut adalah....",
    type: "single",
    image: "/images/questions/indotabel.jpg",
    options: [
      { id: "A", text: "Seorang pasien diduga mengidap pertusis setelah mengalami demam tinggi berhari-hari." },
      { id: "B", text: "Seorang pasien pengidap penyakit pertusis yang telah menjalani satu minggu pemeriksaan." },
      { id: "C", text: "Seorang pasien yang diduga mengalami gejala pertusis setelah dua minggu pemeriksaan." },
      { id: "D", text: "Riwayat penyakit seseorang untuk memastikan dirinya dan keturunannya tidak mengidap pertusis." },
      { id: "E", text: "Tes kesehatan yang dilakukan oleh seorang pasien yang mengalami tanda-tanda penyakit demam berdarah." },
    ],
    correctAnswer: "B",
    explanation: "Tabel tersebut menunjukkan riwayat pemeriksaan seorang pasien pengidap penyakit pertusis dengan gejala-gejala yang muncul pada tahap 1 (1 minggu pertama) dan tahap 2 (setelah 1 minggu).",
  },
  {
    id: 8,
    text: "Bacalah teks berikut dengan cermat!\n\nBahaya polusi udara, air, atau tanah, mungkin sudah kita pahami. Namun, sebenarnya manusia modern juga menghadapi polusi lain yang tak kalah berbahaya, yaitu \"banjir informasi\". Dengan kemudahan mengakses berbagai informasi terkini dari internet, saat ini kita dihadapkan pada jumlah data yang belum pernah terjadi sebelumnya, jauh melampaui kemampuan kita untuk memprosesnya. Hasilnya bisa berdampak negatif pada kesehatan mental, antara lain ketidakmampuan untuk mengevaluasi informasi dan mengambil keputusan dan yang paling sederhana, kita sering mudah percaya dengan hoaks atau pun mitos, termasuk informasi palsu soal kesehatan.\n\nTerlalu sering orang membagikan kehidupan pribadinya di media sosial, terutama memamerkan kesuksesannya, juga terkadang membuat kita merasa tidak percaya diri jika kehidupan kita dirasa kurang beruntung dibanding orang lain. Lebih jauh, kondisi tersebut bisa membuat kita enggan melakukan interaksi sosial, merasa tidak puas dengan pekerjaan, serta kekurangan motivasi.\n\nPara ahli telah memahami dampak buruk dari banjir informasi ini dalam pertemuan internasional dua tahun lalu. Mereka membandingkan fenomena banjir informasi ini dengan pergeseran lain di masyarakat yang historis, misalnya revolusi industri yang melahirkan polusi udara. Setara dengan fenomena itu, \"polusi informasi\" atau \"kabut data\" juga perlu diatasi. \"Informasi yang berlebihan dapat memiliki implikasi yang serius. Ini dimulai dengan mengikis kesehatan mental, performa kerja, dan kepuasan kita, yang kemudian memengaruhi tindakan kelompok dan pada akhirnya, seluruh masyarakat,\" kata Curt Breneman, Ph.D., dekan Sekolah Sains Rensselaer.\n\nTopik teks di atas adalah....",
    type: "single",
    options: [
      { id: "A", text: "Cara mengatasi polusi informasi" },
      { id: "B", text: "Dampak banjir informasi bagi masyarakat" },
      { id: "C", text: "Pro dan kontra banjir informasi menurut ahli" },
      { id: "D", text: "Banjir informasi memengaruhi kesehatan mental" },
      { id: "E", text: "Pendapat para ahli tentang fenomena banjir informasi" },
    ],
    correctAnswer: "B",
    explanation: "Teks tersebut membahas tentang dampak banjir informasi bagi masyarakat, mulai dari dampak negatif pada kesehatan mental, ketidakmampuan mengevaluasi informasi, mudah percaya hoaks, merasa tidak percaya diri, enggan berinteraksi sosial, hingga dampaknya pada performa kerja dan masyarakat secara keseluruhan.",
  },
  {
    id: 9,
    text: "Bacalah teks berikut dengan cermat!\n\nBahaya polusi udara, air, atau tanah, mungkin sudah kita pahami. Namun, sebenarnya manusia modern juga menghadapi polusi lain yang tak kalah berbahaya, yaitu \"banjir informasi\". Dengan kemudahan mengakses berbagai informasi terkini dari internet, saat ini kita dihadapkan pada jumlah data yang belum pernah terjadi sebelumnya, jauh melampaui kemampuan kita untuk memprosesnya. Hasilnya bisa berdampak negatif pada kesehatan mental, antara lain ketidakmampuan untuk mengevaluasi informasi dan mengambil keputusan dan yang paling sederhana, kita sering mudah percaya dengan hoaks atau pun mitos, termasuk informasi palsu soal kesehatan.\n\nTerlalu sering orang membagikan kehidupan pribadinya di media sosial, terutama memamerkan kesuksesannya, juga terkadang membuat kita merasa tidak percaya diri jika kehidupan kita dirasa kurang beruntung dibanding orang lain. Lebih jauh, kondisi tersebut bisa membuat kita enggan melakukan interaksi sosial, merasa tidak puas dengan pekerjaan, serta kekurangan motivasi.\n\nPara ahli telah memahami dampak buruk dari banjir informasi ini dalam pertemuan internasional dua tahun lalu. Mereka membandingkan fenomena banjir informasi ini dengan pergeseran lain di masyarakat yang historis, misalnya revolusi industri yang melahirkan polusi udara. Setara dengan fenomena itu, \"polusi informasi\" atau \"kabut data\" juga perlu diatasi. \"Informasi yang berlebihan dapat memiliki implikasi yang serius. Ini dimulai dengan mengikis kesehatan mental, performa kerja, dan kepuasan kita, yang kemudian memengaruhi tindakan kelompok dan pada akhirnya, seluruh masyarakat,\" kata Curt Breneman, Ph.D., dekan Sekolah Sains Rensselaer.\n\n\n\n\n\nBerdasarkan teks di atas, manakah pernyataan berikut yang tepat mengenai fenomena banjir informasi?",
    type: "single",
    options: [
      { id: "A", text: "Peristiwa di mana pun bisa sampai secara real time" },
      { id: "B", text: "Performa kerja masyarakat menjadi lebih meningkat" },
      { id: "C", text: "Masyarakat menjadi lebih waspada terhadap informasi palsu" },
      { id: "D", text: "Masyakarat mudah percaya hoaks karena terlalu banyak informasi yang diterima" },
      { id: "E", text: "Mempunyai dampak yang positif terhadap kebiasaan masyarakat" },
    ],
    correctAnswer: "D",
    explanation: "Berdasarkan teks, salah satu dampak negatif banjir informasi adalah 'kita sering mudah percaya dengan hoaks atau pun mitos, termasuk informasi palsu soal kesehatan.' Ini menunjukkan bahwa masyarakat mudah percaya hoaks karena terlalu banyak informasi yang diterima.",
  },
  {
    id: 10,
    text: "Berikut ini yang bukan dampak negatif dari fenomena banjir informasi adalah....",
    type: "single",
    options: [
      { id: "A", text: "memiliki kecanduan bermain media sosial" },
      { id: "B", text: "mengakses informasi menjadi lebih mudah" },
      { id: "C", text: "menghindari interaksi sosial secara langsung" },
      { id: "D", text: "menyebarnya informasi hoaks atau berita palsu" },
      { id: "E", text: "mudah memercayai diagnosa kesehatan dari internet" },
    ],
    correctAnswer: "B",
    explanation: "Mengakses informasi menjadi lebih mudah adalah dampak positif dari perkembangan teknologi informasi, bukan dampak negatif dari fenomena banjir informasi. Dampak negatif yang disebutkan dalam teks meliputi ketidakmampuan mengevaluasi informasi, mudah percaya hoaks, merasa tidak percaya diri, enggan berinteraksi sosial, dan dampak pada kesehatan mental.",
  },
  {
    id: 11,
    text: "Bacalah teks berikut dengan cermat!\n\nPersoalan mengenai sampah menjadi permasalahan global tak terkecuali di Indonesia. Peningkatan sampah secara langsung berkaitan dengan peningkatan penduduk yang mendorong kenaikan tingkat konsumsi. Berdasarkan data Badan Pusat Statistik (BPS) dan Kementerian Lingkungan Hidup (KLHK), menyatakan timbulan sampah per 2019 sebesar 67,10 juta ton dan pada tahun 2020 mencapai 67,80 ton.\n\nKeseluruhan jenis sampah organik maupun anorganik dapat menyebabkan kerusakan ekologis bagi lingkungan. Dampak negatif yang ditimbulkan dari sampah dirasakan secara langsung dalam berbagai aspek, mulai dari lingkungan, kesehatan, sosial, hingga ekonomi. Pengolahan sampah yang buruk dapat merusak kelestarian lingkungan, serta mengganggu kesehatan masyarakat.\n\nSalah satu bentuk inovasi pengolahan sampah dapat dilakukan dengan pembangunan Pembangkit Listrik Tenaga Sampah (PLTSa). PLTSa ini bermanfaat sebagai pembangkit listrik dan menjaga kebersihan lingkungan dengan meminimalisasi jumlah sampah, dan mengurangi emisi gas karbon. Sebagian besar sampah yang akan digunakan di PLTSa adalah sampah organik dengan potensi racun yang relatif lebih rendah. Sampah ini nantinya digunakan sebagai bahan bakar untuk memanaskan air dalam boiler. Uap panas yang dihasilkan akan dimasukkan ke turbin uap untuk memutar generator sehingga listrik dapat dihasilkan.\n\nPengolahan sampah pada PLTSa menggunakan teknologi ternal jenis insinerasi. Teknologi termal jenis insinerasi merupakan teknologi proven yang digunakan di berbagai negara sejak dahulu dan dapat memusnahkan sampah yang tercampur, sehingga cocok dikembangkan di Indonesia yang kondisi sampahnya merupakan sampah campuran. Sampah-sampah tersebut dapat digolongkan dalam beberapa kriteria berdasarkan sifat, bentuk, dan sumber sebagai berikut.\n\nTabel Klasifikasi Sampah\nJenis | Contoh\n--- | ---\nOrganik | Sisa makanan, sisa sayuran, dan sampah tanaman, rumput-rumputan, sekam padi.\nAnorganik | Kertas, kardus, botol kaca, kaleng, logam, kantong plastik, aluminium, karton.\nSampah Bahan Berbahaya Beracun (B3) | Sampah medis, sampah elektronik, cairan kimia dan pelumas, produk kedaluarsa, dan beberapa sampah lainnya dengan karakteristik mudah meledak, terbakar, bersifat korosif, karsinogenik, dan dapat mengiritasi.\n\nPernyataan yang tepat mengenai kondisi sampah di Indonesia adalah....",
    type: "single",
    image: "/images/questions/indos.jpg",
    options: [
      { id: "A", text: "Indonesia tidak memerlukan PLTSa untuk pengelolaan sampah." },
      { id: "B", text: "Sampah di Indonesia sudah teratasi dengan baik." },
      { id: "C", text: "Pada 2019 timbulan sampah mencapai 67,80 ton." },
      { id: "D", text: "Timbulan sampah di Indonesia belum diklasifikasikan." },
      { id: "E", text: "Timbulan sampah meningkat seiring pertumbuhan penduduk dan konsumsi." },
    ],
    correctAnswer: "E",
    explanation: "Teks menyebutkan bahwa peningkatan sampah berkaitan dengan pertumbuhan penduduk dan konsumsi. Maka pernyataan tersebut lebih tepat dan sesuai konteks teks."
  },
  {
    id: 12,
    text: "Berikut ini merupakan jenis sampah yang dapat dijadikan bahan bakar dari PLTSa....",
    image: "/images/questions/indos.jpg",
    type: "single",
    options: [
      { id: "A", text: "sekam padi, kaleng, lampu, kabel, daging" },
      { id: "B", text: "sisa sayuran, aluminium, gawai, piring kaca" },
      { id: "C", text: "karton, sampah tanaman, botol kaca, masker" },
      { id: "D", text: "daun kering, buah-buahan, daging, sekam padi" },
      { id: "E", text: "rumput-rumputan, kantong plastik, pecahan kaca" },
    ],
    correctAnswer: "D",
    explanation: "Berdasarkan teks, 'Sebagian besar sampah yang akan digunakan di PLTSa adalah sampah organik dengan potensi racun yang relatif lebih rendah.' Dari pilihan yang tersedia, opsi D (daun kering, buah-buahan, daging, sekam padi) merupakan sampah organik yang dapat dijadikan bahan bakar PLTSa.",
  },
  {
    id: 13,
    text: "Salah satu manfaat pembangunan Pembangkit Listrik Tenaga Sampah (PLTSa) adalah....",
    type: "single",
    image: "/images/questions/indos.jpg",
    options: [
      { id: "A", text: "menghasilkan emisi gas karbon" },
      { id: "B", text: "menjaga kebersihan lingkungan" },
      { id: "C", text: "menggunakan jenis sampah anorganik" },
      { id: "D", text: "mengeluarkan limbah berupa polusi udara" },
      { id: "E", text: "membutuhkan biaya besar untuk bahan bakar" },
    ],
    correctAnswer: "B",
    explanation: "Berdasarkan teks, 'PLTSa ini bermanfaat sebagai pembangkit listrik dan menjaga kebersihan lingkungan dengan meminimalisasi jumlah sampah, dan mengurangi emisi gas karbon.' Jadi, salah satu manfaat PLTSa adalah menjaga kebersihan lingkungan.",
  },
  {
    id: 14,
    text: "Dampak negatif yang dapat ditimbulkan sampah dari aspek kesehatan adalah....",
    type: "single",
    image: "/images/questions/indos.jpg",
    options: [
      { id: "A", text: "menyebarkan bau tidak sedap" },
      { id: "B", text: "menyebabkan air sungai tercemar" },
      { id: "C", text: "menyebarkan penyakit diare dan DBD" },
      { id: "D", text: "menyebabkan lingkungan menjadi kumuh" },
      { id: "E", text: "menimbulkan pemandangan yang buruk" },
    ],
    correctAnswer: "C",
    explanation: "Dampak negatif sampah dari aspek kesehatan adalah menyebarkan penyakit, seperti diare dan DBD. Teks menyebutkan bahwa 'Dampak negatif yang ditimbulkan dari sampah dirasakan secara langsung dalam berbagai aspek, mulai dari lingkungan, kesehatan, sosial, hingga ekonomi.' Meskipun tidak disebutkan secara spesifik penyakit apa yang ditimbulkan, opsi C adalah yang paling relevan dengan aspek kesehatan.",
  },
  {
    id: 15,
    text: "Bacalah teks berikut dengan cermat!\n\n\"Ketemu besok pagi ya, Adik Manis,\" kata seseorang tak dikenal itu sambil berulang menepuk lengan kiri Acil. Seseorang itu memakai topi putih dan kacamata hitam. Acil tak merasa asing karena merasa sering bertemu orang itu. Orang yang mirip sekali dengan Kang Maman, tetangga dekatnya.\n\nPergi pagi, pulang sore, rupanya sudah menjadi kebiasaan Acil dan anak-anak lain kampung itu. Namun, saat itu kesabaran Emak ternyata telah sampai batasnya. Emak mulai cemas saat pukul tujuh malam Acil belum juga pulang. Atas perintah Emak, pada pukul delapan malam, Hariman dan Bapak bergegas mencari Acil. Mereka pergi ke rumah Kang Maman, ke pasar kecamatan, lalu ke rumah kawan-kawan Acil, tetapi Acil tak juga ditemukan. Setelah Hariman dan Bapak pulang ke rumah tanpa membawa Acil, Emak menangis sampai pagi. Tangisan Emak berhenti saat Hariman membawa kabar bahwa Acil telah ditemukan. Pada pukul enam sore, ketika berdiri kelelahan mencari Acil di jalan kecil dekat petak sawah tak jauh dari rumah mereka, Hariman mencium bau bangkai. Hidungnya yang pesek mengendus dan mengikuti arah bau yang membuat perutnya mual. Hariman melihat sesosok anak kecil dalam posisi telungkup di petak sawah. Hariman mendekat, lalu menjerit saat menyadari bahwa mayat yang telungkup di air dangkal itu adalah mayat adiknya. Tak butuh waktu lama, Hariman sudah bisa mengenali ciri-ciri adiknya: kaus biru dan celana panjang hitam yang membungkus mayat itu adalah pakaian yang sama yang dikenakan Acil saat shalat subuh kemarin. Hariman lekas lari pulang ke rumah untuk memberi kabar pada Emak dan Bapak, dan kabar itulah yang membuat tangis Emak berhenti mendadak. Sudut pandang yang digunakan dalam cerita tersebut adalah....",
    type: "single",
    options: [
      { id: "A", text: "Orang pertama pelaku utama" },
      { id: "B", text: "Orang pertama pelaku sampingan" },
      { id: "C", text: "Orang ketiga terbatas" },
      { id: "D", text: "Orang ketiga serba tahu" },
      { id: "E", text: "Orang ketiga pengamat" },
    ],
    correctAnswer: "C",
    explanation: "Narator hanya menggambarkan tindakan tokoh-tokoh tanpa menyampaikan isi pikiran mereka. Oleh karena itu, sudut pandang yang digunakan adalah orang ketiga terbatas, bukan serba tahu."
  },
  {
    id: 16,
    text: "Bacalah teks berikut dengan cermat!\n\n\"Ketemu besok pagi ya, Adik Manis,\" kata seseorang tak dikenal itu sambil berulang menepuk lengan kiri Acil. Seseorang itu memakai topi putih dan kacamata hitam. Acil tak merasa asing karena merasa sering bertemu orang itu. Orang yang mirip sekali dengan Kang Maman, tetangga dekatnya.\n\nPergi pagi, pulang sore, rupanya sudah menjadi kebiasaan Acil dan anak-anak lain kampung itu. Namun, saat itu kesabaran Emak ternyata telah sampai batasnya. Emak mulai cemas saat pukul tujuh malam Acil belum juga pulang. Atas perintah Emak, pada pukul delapan malam, Hariman dan Bapak bergegas mencari Acil. Mereka pergi ke rumah Kang Maman, ke pasar kecamatan, lalu ke rumah kawan-kawan Acil, tetapi Acil tak juga ditemukan. Setelah Hariman dan Bapak pulang ke rumah tanpa membawa Acil, Emak menangis sampai pagi. Tangisan Emak berhenti saat Hariman membawa kabar bahwa Acil telah ditemukan. Pada pukul enam sore, ketika berdiri kelelahan mencari Acil di jalan kecil dekat petak sawah tak jauh dari rumah mereka, Hariman mencium bau bangkai. Hidungnya yang pesek mengendus dan mengikuti arah bau yang membuat perutnya mual. Hariman melihat sesosok anak kecil dalam posisi telungkup di petak sawah. Hariman mendekat, lalu menjerit saat menyadari bahwa mayat yang telungkup di air dangkal itu adalah mayat adiknya. Tak butuh waktu lama, Hariman sudah bisa mengenali ciri-ciri adiknya: kaus biru dan celana panjang hitam yang membungkus mayat itu adalah pakaian yang sama yang dikenakan Acil saat shalat subuh kemarin. Hariman lekas lari pulang ke rumah untuk memberi kabar pada Emak dan Bapak, dan kabar itulah yang membuat tangis Emak berhenti mendadak. \n\n\n\n\n\n\nHikmah yang dapat dipetik dari kutipan cerita tersebut adalah....",
    type: "single",
    options: [
      { id: "A", text: "Jangan membiarkan anak pulang larut" },
      { id: "B", text: "Jangan mudah memercayai orang asing" },
      { id: "C", text: "Selalu perhatikan orang-orang sekitarmu" },
      { id: "D", text: "Membantu sesama merupakan contoh baik" },
      { id: "E", text: "Hindari interaksi dan sosialisasi dengan orang" },
    ],
    correctAnswer: "B",
    explanation: "Hikmah yang dapat dipetik dari cerita tersebut adalah jangan mudah memercayai orang asing. Cerita menggambarkan bagaimana Acil mempercayai seseorang yang tidak dikenal (meskipun mirip dengan tetangganya) dan berjanji untuk bertemu dengannya, yang berujung pada kematian Acil.",
  },
  {
    id: 17,
    text: "Bacalah teks berikut dengan cermat!\n\n\"Ketemu besok pagi ya, Adik Manis,\" kata seseorang tak dikenal itu sambil berulang menepuk lengan kiri Acil. Seseorang itu memakai topi putih dan kacamata hitam. Acil tak merasa asing karena merasa sering bertemu orang itu. Orang yang mirip sekali dengan Kang Maman, tetangga dekatnya.\n\nPergi pagi, pulang sore, rupanya sudah menjadi kebiasaan Acil dan anak-anak lain kampung itu. Namun, saat itu kesabaran Emak ternyata telah sampai batasnya. Emak mulai cemas saat pukul tujuh malam Acil belum juga pulang. Atas perintah Emak, pada pukul delapan malam, Hariman dan Bapak bergegas mencari Acil. Mereka pergi ke rumah Kang Maman, ke pasar kecamatan, lalu ke rumah kawan-kawan Acil, tetapi Acil tak juga ditemukan. Setelah Hariman dan Bapak pulang ke rumah tanpa membawa Acil, Emak menangis sampai pagi. Tangisan Emak berhenti saat Hariman membawa kabar bahwa Acil telah ditemukan. Pada pukul enam sore, ketika berdiri kelelahan mencari Acil di jalan kecil dekat petak sawah tak jauh dari rumah mereka, Hariman mencium bau bangkai. Hidungnya yang pesek mengendus dan mengikuti arah bau yang membuat perutnya mual. Hariman melihat sesosok anak kecil dalam posisi telungkup di petak sawah. Hariman mendekat, lalu menjerit saat menyadari bahwa mayat yang telungkup di air dangkal itu adalah mayat adiknya. Tak butuh waktu lama, Hariman sudah bisa mengenali ciri-ciri adiknya: kaus biru dan celana panjang hitam yang membungkus mayat itu adalah pakaian yang sama yang dikenakan Acil saat shalat subuh kemarin. Hariman lekas lari pulang ke rumah untuk memberi kabar pada Emak dan Bapak, dan kabar itulah yang membuat tangis Emak berhenti mendadak.\n\n\n\n\n\n\n\n\n  Kutipan berikut yang tidak menunjukkan latar cerita adalah....",
    type: "single",
    options: [
      { id: "A", text: "Emak mulai cemas saat pukul tujuh malam Acil belum juga pulang." },
      { id: "B", text: "Tak butuh waktu lama, Hariman sudah bisa mengenali ciri-ciri adiknya." },
      { id: "C", text: "Pada pukul delapan malam, Hariman dan Bapak bergegas mencari Acil." },
      { id: "D", text: "Hariman melihat sesosok anak kecil dalam posisi telungkup di petak sawah." },
      { id: "E", text: "Mereka pergi ke rumah Kang Maman, ke pasar kecamatan, lalu ke rumah kawan-kawan Acil." },
    ],
    correctAnswer: "B",
    explanation: "Kutipan 'Tak butuh waktu lama, Hariman sudah bisa mengenali ciri-ciri adiknya' tidak menunjukkan latar cerita (waktu, tempat, atau suasana), melainkan menggambarkan tindakan tokoh Hariman.",
  },
  {
    id: 18,
    text: "Bacalah teks berikut dengan cermat!\n\n\"Ketemu besok pagi ya, Adik Manis,\" kata seseorang tak dikenal itu sambil berulang menepuk lengan kiri Acil. Seseorang itu memakai topi putih dan kacamata hitam. Acil tak merasa asing karena merasa sering bertemu orang itu. Orang yang mirip sekali dengan Kang Maman, tetangga dekatnya.\n\nPergi pagi, pulang sore, rupanya sudah menjadi kebiasaan Acil dan anak-anak lain kampung itu. Namun, saat itu kesabaran Emak ternyata telah sampai batasnya. Emak mulai cemas saat pukul tujuh malam Acil belum juga pulang. Atas perintah Emak, pada pukul delapan malam, Hariman dan Bapak bergegas mencari Acil. Mereka pergi ke rumah Kang Maman, ke pasar kecamatan, lalu ke rumah kawan-kawan Acil, tetapi Acil tak juga ditemukan. Setelah Hariman dan Bapak pulang ke rumah tanpa membawa Acil, Emak menangis sampai pagi. Tangisan Emak berhenti saat Hariman membawa kabar bahwa Acil telah ditemukan. Pada pukul enam sore, ketika berdiri kelelahan mencari Acil di jalan kecil dekat petak sawah tak jauh dari rumah mereka, Hariman mencium bau bangkai. Hidungnya yang pesek mengendus dan mengikuti arah bau yang membuat perutnya mual. Hariman melihat sesosok anak kecil dalam posisi telungkup di petak sawah. Hariman mendekat, lalu menjerit saat menyadari bahwa mayat yang telungkup di air dangkal itu adalah mayat adiknya. Tak butuh waktu lama, Hariman sudah bisa mengenali ciri-ciri adiknya: kaus biru dan celana panjang hitam yang membungkus mayat itu adalah pakaian yang sama yang dikenakan Acil saat shalat subuh kemarin. Hariman lekas lari pulang ke rumah untuk memberi kabar pada Emak dan Bapak, dan kabar itulah yang membuat tangis Emak berhenti mendadak.\n\n\n\n\n\n\n\n\nKutipan yang menunjukkan suasana duka dalam cerita di atas adalah....",
    type: "single",
    options: [
      { id: "A", text: "Setelah Hariman dan Bapak pulang ke rumah tanpa membawa Acil, Emak menangis sampai pagi." },
      { id: "B", text: "Seseorang itu memakai topi putih dan kacamata hitam. Acil tak merasa asing karena merasa sering bertemu orang itu." },
      { id: "C", text: "\"Ketemu besok pagi ya, Adik Manis,\" kata seseorang tak dikenal itu sambil berulang menepuk lengan kiri Acil." },
      { id: "D", text: "Pergi pagi, pulang sore, rupanya sudah menjadi kebiasaan Acil dan anak-anak lain kampung itu." },
      { id: "E", text: "Atas perintah Emak, pada pukul delapan malam, Hariman dan Bapak bergegas mencari Acil." },
    ],
    correctAnswer: "A",
    explanation: "Kutipan 'Setelah Hariman dan Bapak pulang ke rumah tanpa membawa Acil, Emak menangis sampai pagi' menunjukkan suasana duka karena menggambarkan kesedihan Emak yang menangis sepanjang malam karena Acil tidak ditemukan.",
  },
  {
    id: 19,
    text: "Bacalah teks berikut dengan cermat!\n\nDoenia Kita menyebut Nyonya Soejono dengan predikat schoonheidspecialiste alias ahli kecantikan. Asalnya dari Surabaya dan disebut-sebut sebagai \"wanita kelahiran Indonesia pertama yang berkecimpung di bidang perawatan wajah\". Saat artikel itu terbit, nama Nyonya Soejono sudah demikian masyhur, terutama di kalangan perempuan kelas menengah atas. Namun, gaung namanya memudar seiring waktu dan kini dia hampir tak dikenal.\n\nSumber sejarah tentang masa kecil Nyonya Soejono tidaklah banyak. Yang terang, Nyonya Soejono mengaku memiliki nama gadis Soefina dan lahir dalam keluarga ningrat di Surabaya. Soefina lalu menikah dengan Raden Harjo Soejono dan sejak itulah orang menyapanya Nyonya Soejono. Dalam sebuah wawancara yang juga terbit Doenia Kita (Agustus 1939), Nyonya Soejono mengaku bahwa mulanya menekuni perawatan kecantikan adalah untuk keperluannya sendiri. Rupanya hal ini juga dipengaruhi oleh interaksinya dengan Dokter Soetomo. Beliaulah yang mengajari Nyonya Soejono berbagai ilmu dan resep obat kecantikan. Interaksi ini terjalin melalui sang suami yang merupakan kolega Dokter Soetomo kala mendirikan perkumpulan Indonesische Studieclub pada 1924.\n\nPertanyaan yang jawabannya terdapat di dalam teks adalah...",
    type: "single",
    options: [
      { id: "A", text: "Apa alasan Raden Harjo Soejono menikahi Soefina?" },
      { id: "B", text: "Apa tujuan Nyonya Soejono menekuni bidang kecantikan?" },
      { id: "C", text: "Bagaimana karier dr. Soetomo setelah mengenal Nyonya Soejono?" },
      { id: "D", text: "Mengapa Nyonya Soejono lambat laun dilupakan oleh masyarakat Indonesia?" },
      { id: "E", text: "Mengapa ahli kecantikan wajah hanya terkenal di kalangan wanita menengah ke atas?" },
    ],
    correctAnswer: "B",
    explanation: "Pertanyaan 'Apa tujuan Nyonya Soejono menekuni bidang kecantikan?' jawabannya terdapat dalam teks, yaitu 'Nyonya Soejono mengaku bahwa mulanya menekuni perawatan kecantikan adalah untuk keperluannya sendiri.'",
  },
  {
    id: 20,
    text: "Bacalah teks berikut dengan cermat!\n\nDoenia Kita menyebut Nyonya Soejono dengan predikat schoonheidspecialiste alias ahli kecantikan. Asalnya dari Surabaya dan disebut-sebut sebagai \"wanita kelahiran Indonesia pertama yang berkecimpung di bidang perawatan wajah\". Saat artikel itu terbit, nama Nyonya Soejono sudah demikian masyhur, terutama di kalangan perempuan kelas menengah atas. Namun, gaung namanya memudar seiring waktu dan kini dia hampir tak dikenal.\n\nSumber sejarah tentang masa kecil Nyonya Soejono tidaklah banyak. Yang terang, Nyonya Soejono mengaku memiliki nama gadis Soefina dan lahir dalam keluarga ningrat di Surabaya. Soefina lalu menikah dengan Raden Harjo Soejono dan sejak itulah orang menyapanya Nyonya Soejono. Dalam sebuah wawancara yang juga terbit Doenia Kita (Agustus 1939), Nyonya Soejono mengaku bahwa mulanya menekuni perawatan kecantikan adalah untuk keperluannya sendiri. Rupanya hal ini juga dipengaruhi oleh interaksinya dengan Dokter Soetomo. Beliaulah yang mengajari Nyonya Soejono berbagai ilmu dan resep obat kecantikan. Interaksi ini terjalin melalui sang suami yang merupakan kolega Dokter Soetomo kala mendirikan perkumpulan Indonesische Studieclub pada 1924.\n\n\n\n\nn\n\\n\n\n\n\nnPernyataan yang sesuai dengan isi teks di atas adalah...",
    type: "single",
    options: [
      { id: "A", text: "Seluruh masyarakat Indonesia kini sudah tidak mengenal lagi sosok Nyonya Soejono." },
      { id: "B", text: "Alasan Nyonya Soejono menekuni bidang kecantikan karena pengaruh dr. Soetomo." },
      { id: "C", text: "Wanita kelas menengah ke atas memiliki ketertarikan yang lebih pada bidang kecantikan." },
      { id: "D", text: "Pada tahun 1930-an, Nyonya Soejono adalah satu-satunya ahli di bidang kecantikan wajah." },
      { id: "E", text: "Perawatan kecantikan wajah sudah menjadi tren sejak Indonesia belum mencapai kemerdekaan." },
    ],
    correctAnswer: "E",
    explanation: "Pernyataan 'Perawatan kecantikan wajah sudah menjadi tren sejak Indonesia belum mencapai kemerdekaan' sesuai dengan isi teks. Teks menyebutkan bahwa pada tahun 1939 (sebelum kemerdekaan Indonesia), nama Nyonya Soejono sudah masyhur di kalangan perempuan kelas menengah atas sebagai ahli kecantikan.",
  },
  {
    id: 21,
    text: "Bacalah teks berikut dengan cermat!\n\nDoenia Kita menyebut Nyonya Soejono dengan predikat schoonheidspecialiste alias ahli kecantikan. Asalnya dari Surabaya dan disebut-sebut sebagai \"wanita kelahiran Indonesia pertama yang berkecimpung di bidang perawatan wajah\". Saat artikel itu terbit, nama Nyonya Soejono sudah demikian masyhur, terutama di kalangan perempuan kelas menengah atas. Namun, gaung namanya memudar seiring waktu dan kini dia hampir tak dikenal.\n\nSumber sejarah tentang masa kecil Nyonya Soejono tidaklah banyak. Yang terang, Nyonya Soejono mengaku memiliki nama gadis Soefina dan lahir dalam keluarga ningrat di Surabaya. Soefina lalu menikah dengan Raden Harjo Soejono dan sejak itulah orang menyapanya Nyonya Soejono. Dalam sebuah wawancara yang juga terbit Doenia Kita (Agustus 1939), Nyonya Soejono mengaku bahwa mulanya menekuni perawatan kecantikan adalah untuk keperluannya sendiri. Rupanya hal ini juga dipengaruhi oleh interaksinya dengan Dokter Soetomo. Beliaulah yang mengajari Nyonya Soejono berbagai ilmu dan resep obat kecantikan. Interaksi ini terjalin melalui sang suami yang merupakan kolega Dokter Soetomo kala mendirikan perkumpulan Indonesische Studieclub pada 1924.\n\\n\n\n\n\n\nn\nBerdasarkan teks di atas, peran Soejono untuk istrinya yang bergelut di bidang kecantikan adalah....",
    type: "single",
    options: [
      { id: "A", text: "turut serta menekuni bidang kecantikan bersama istri." },
      { id: "B", text: "menikahi Soefina karena berasal dari keluarga ningrat." },
      { id: "C", text: "mengajari istrinya tentang ilmu dan resep di bidang tersebut." },
      { id: "D", text: "mendukung minat istri dalam mempercantik diri dan merawat diri." },
      { id: "E", text: "mengenalkan istrinya kepada koleganya yang bernama dr. Soetomo." },
    ],
    correctAnswer: "E",
    explanation: "Berdasarkan teks, peran Soejono untuk istrinya yang bergelut di bidang kecantikan adalah mengenalkan istrinya kepada koleganya yang bernama dr. Soetomo. Teks menyebutkan 'Interaksi ini terjalin melalui sang suami yang merupakan kolega Dokter Soetomo kala mendirikan perkumpulan Indonesische Studieclub pada 1924.'",
  },
  {
    id: 22,
    text: "Bacalah teks berikut dengan cermat!\n\nSitus Lebak Cibedug merupakan situs punden berundak berdenah segi empat yang terbagi dalam beberapa tingkatan ruang atau halaman. Di beberapa terasnya bisa terlihat formasi batu yang membentuk semacam altar dan menhir. Kompleks situs ini berorientasi ke barat dan dibuat semakin tinggi ke arah timur. Jalan atau pintu masuknya berada di sebelah barat melalui anak tangga.\n\nMenurut studi Agus Aris Munandar dkk. dalam Bangunan Suci Sunda Kuno (2011, hlm. 121), Situs Lebak Cibedug memiliki kesamaan tipologi dengan punden-punden berundak yang ada di Tatar Sunda. Hal itu dicirikan dari struktur undakan yang dindingnya disusun dari batu-batu alami dan permukaan teras-terasnya juga ditutup dengan batu-batu—orang Sunda menyebutnya dibalay.\n\nPenelitian arkeologis menunjukkan bahwa punden berundak Lebak Cibedug ataupun punden berundak lain yang berada di sekitar kawasan Banten dan Jawa Barat diperkirakan dibangun pada masa Neolitik (sekira 2500-1500 SM). Situs Megalitik Lebak Cibedug menyimpan serbaneka tinggalan prasejarah yang bervariasi, seperti menhir, batu tegak, batu datar, dan takhta batu dengan punden berundak sebagai bagian yang sakral. Selain itu, di sekitar area situs juga tersebar beberapa tinggalan prasejarah.\n\n\n\n\n\n\nInti bacaan yang dibahas di dalam teks di atas adalah....",
    type: "single",
    options: [
      { id: "A", text: "ciri khas situs Lebak Cibedug" },
      { id: "B", text: "bahan penyusun situs Lebak Cibedug" },
      { id: "C", text: "situs punden berundak Lebak Cibedug" },
      { id: "D", text: "hasil tinggalan prasejarah Lebak Cibedug" },
      { id: "E", text: "kesamaan situs Lebak Cibedug dengan situs lainnya" },
    ],
    correctAnswer: "C",
    explanation: "Inti bacaan yang dibahas dalam teks adalah situs punden berundak Lebak Cibedug. Teks menjelaskan tentang struktur, orientasi, tipologi, perkiraan waktu pembangunan, dan tinggalan prasejarah yang terdapat di situs tersebut.",
  },
  {
    id: 23,
    text: "Bacalah teks berikut dengan cermat!\n\nSitus Lebak Cibedug merupakan situs punden berundak berdenah segi empat yang terbagi dalam beberapa tingkatan ruang atau halaman. Di beberapa terasnya bisa terlihat formasi batu yang membentuk semacam altar dan menhir. Kompleks situs ini berorientasi ke barat dan dibuat semakin tinggi ke arah timur. Jalan atau pintu masuknya berada di sebelah barat melalui anak tangga.\n\nMenurut studi Agus Aris Munandar dkk. dalam Bangunan Suci Sunda Kuno (2011, hlm. 121), Situs Lebak Cibedug memiliki kesamaan tipologi dengan punden-punden berundak yang ada di Tatar Sunda. Hal itu dicirikan dari struktur undakan yang dindingnya disusun dari batu-batu alami dan permukaan teras-terasnya juga ditutup dengan batu-batu—orang Sunda menyebutnya dibalay.\n\nPenelitian arkeologis menunjukkan bahwa punden berundak Lebak Cibedug ataupun punden berundak lain yang berada di sekitar kawasan Banten dan Jawa Barat diperkirakan dibangun pada masa Neolitik (sekira 2500-1500 SM). Situs Megalitik Lebak Cibedug menyimpan serbaneka tinggalan prasejarah yang bervariasi, seperti menhir, batu tegak, batu datar, dan takhta batu dengan punden berundak sebagai bagian yang sakral. Selain itu, di sekitar area situs juga tersebar beberapa tinggalan prasejarah.\n\n\n\n\n\n\nBerikut merupakan pernyataan yang sesuai dengan teks di atas adalah...",
    type: "single",
    options: [
      { id: "A", text: "Situs Lebak Cibedug sering digunakan untuk acara-acara sakral." },
      { id: "B", text: "Situs Lebak Cibedug berada di sekitaran kawasan Banten dan Jawa Barat." },
      { id: "C", text: "Situs Lebak Cibedug merupakan peninggalan megalitikum khas suku Sunda." },
      { id: "D", text: "Berbagai jenis tinggalan prasejarah dapat ditemukan di situs Lebak Cibedug." },
      { id: "E", text: "Keunikan dari situs Lebak Cibedug adalah permukaan terasnya ditutup dengan batu." },
    ],
    correctAnswer: "D",
    explanation: "Pernyataan 'Berbagai jenis tinggalan prasejarah dapat ditemukan di situs Lebak Cibedug' sesuai dengan teks. Teks menyebutkan 'Situs Megalitik Lebak Cibedug menyimpan serbaneka tinggalan prasejarah yang bervariasi, seperti menhir, batu tegak, batu datar, dan takhta batu dengan punden berundak sebagai bagian yang sakral.'",
  },
  {
    id: 24,
    text: "Bacalah teks berikut dengan cermat!\n\nSitus Lebak Cibedug merupakan situs punden berundak berdenah segi empat yang terbagi dalam beberapa tingkatan ruang atau halaman. Di beberapa terasnya bisa terlihat formasi batu yang membentuk semacam altar dan menhir. Kompleks situs ini berorientasi ke barat dan dibuat semakin tinggi ke arah timur. Jalan atau pintu masuknya berada di sebelah barat melalui anak tangga.\n\nMenurut studi Agus Aris Munandar dkk. dalam Bangunan Suci Sunda Kuno (2011, hlm. 121), Situs Lebak Cibedug memiliki kesamaan tipologi dengan punden-punden berundak yang ada di Tatar Sunda. Hal itu dicirikan dari struktur undakan yang dindingnya disusun dari batu-batu alami dan permukaan teras-terasnya juga ditutup dengan batu-batu—orang Sunda menyebutnya dibalay.\n\nPenelitian arkeologis menunjukkan bahwa punden berundak Lebak Cibedug ataupun punden berundak lain yang berada di sekitar kawasan Banten dan Jawa Barat diperkirakan dibangun pada masa Neolitik (sekira 2500-1500 SM). Situs Megalitik Lebak Cibedug menyimpan serbaneka tinggalan prasejarah yang bervariasi, seperti menhir, batu tegak, batu datar, dan takhta batu dengan punden berundak sebagai bagian yang sakral. Selain itu, di sekitar area situs juga tersebar beberapa tinggalan prasejarah.\n\n\n\n\n\n\nKata Tatar Sunda pada teks di atas dapat diganti dengan....",
    type: "single",
    options: [
      { id: "A", text: "budaya suku Sunda" },
      { id: "B", text: "wilayah suku Sunda" },
      { id: "C", text: "pemukiman suku Sunda" },
      { id: "D", text: "masyarakat suku Sunda" },
      { id: "E", text: "adat istiadat suku Sunda" },
    ],
    correctAnswer: "B",
    explanation: "Tatar Sunda merujuk pada wilayah budaya atau geografis suku Sunda, sehingga padanan yang lebih tepat adalah 'wilayah suku Sunda'."
  },
  {
    id: 25,
    text: "Bacalah teks berikut dengan cermat!\n\nDunia internasional semakin menyoroti bertambahnya jumlah pelajar perempuan di Negara I yang jatuh sakit selama beberapa bulan ke belakang diduga akibat serangan kimia. Meski sumber-sumber menyebutkan angka yang berbeda-beda, per 7 Maret banyak laporan mencatat ada lebih dari 1.000 kasus keracunan. Ini terjadi di setidaknya 58 sekolah di 10 provinsi Negara I.\n\nKasus-kasus paling awal dilaporkan di Kota Q pada bulan November lalu. Jumlah kasusnya kemudian semakin bertambah, yaitu 26 sekolah melaporkan gelombang insiden keracunan hanya dalam seminggu ke belakang. Para murid mengeluhkan gejala pernapasan, mual, pusing, dan rasa lelah. Beberapa dari mereka sampai masuk rumah sakit. Para orang tua pun memutuskan merumahkan dulu anak perempuan mereka demi terhindar dari serangan-serangan ini. Keresahan publik yang meningkat disertai perhatian dunia internasional membuat Pemimpin Tertinggi Negara I secara publik mengutuk serangan-serangan tersebut sebagai \"kejahatan besar yang tidak bisa dimaafkan\". Ia menjanjikan investigasi dan hukuman secepatnya bagi mereka yang bertanggung jawab.\n\nBanyak pihak menganggap serangan-serangan ini sebagai balasan terhadap gelombang protes yang tengah berlangsung di Negara I sejak kematian seorang aktivis pada bulan September. Berbagai pelajar, sebagian besar mahasiswa dan murid perempuan, ada di garda terdepan dalam rangkaian demonstrasi tersebut.\n\nPernyataan yang tidak sesuai dengan teks di atas adalah...",
    type: "single",
    options: [
      { id: "A", text: "Kasus keracunan pelajar perempuan di Negara I mendapat sorotan internasional." },
      { id: "B", text: "Pemimpin tertinggi Negara I mengutuk peristiwa yang menimpa pelajar perempuan." },
      { id: "C", text: "Kasus serangan kimia terhadap pelajar perempuan paling parah terjadi di Kota Q." },
      { id: "D", text: "Pemerintah Negara I akan menyelidiki serangan kimia yang terjadi di sekolah." },
      { id: "E", text: "Serangan kimia dipandang sebagai serangan balasan terhadap demonstrasi." },
    ],
    correctAnswer: "C",
    explanation: "Pernyataan 'Kasus serangan kimia terhadap pelajar perempuan paling parah terjadi di Kota Q' tidak sesuai dengan teks. Teks hanya menyebutkan bahwa kasus-kasus paling awal dilaporkan di Kota Q, bukan kasus yang paling parah.",
  },
    {
      id: 26,
      text: "Bacalah paragraf berikut:\n\nTeknologi telah mengubah cara kita belajar. Dengan adanya internet dan perangkat digital, akses terhadap informasi dan pengetahuan menjadi lebih mudah. Siswa dapat belajar kapan saja dan di mana saja. Namun, penggunaan teknologi dalam pembelajaran juga memiliki tantangan, seperti kesenjangan digital dan potensi gangguan konsentrasi.\n\nGagasan utama paragraf tersebut adalah...",
      options: [
        { id: "A", text: "Dampak teknologi terhadap cara belajar" },
        { id: "B", text: "Kemudahan akses informasi melalui internet" },
        { id: "C", text: "Tantangan dalam penggunaan teknologi untuk pembelajaran" },
        { id: "D", text: "Pentingnya belajar kapan saja dan di mana saja" },
      ],
      correctAnswer: "A",
      explanation:
        "Gagasan utama paragraf tersebut adalah dampak teknologi terhadap cara belajar. Kalimat pertama langsung menyatakan gagasan ini, dan kalimat-kalimat selanjutnya menjelaskan dampak positif dan negatif teknologi terhadap pembelajaran.",
    },
    {
      id: 27,
      text: "Bacalah paragraf berikut:\n\nPembangunan berkelanjutan merupakan konsep pembangunan yang memenuhi kebutuhan saat ini tanpa mengorbankan kemampuan generasi mendatang untuk memenuhi kebutuhan mereka. Konsep ini mencakup tiga aspek utama: ekonomi, sosial, dan lingkungan. Pembangunan berkelanjutan bertujuan untuk mencapai keseimbangan antara pertumbuhan ekonomi, kesejahteraan sosial, dan pelestarian lingkungan.\n\nPernyataan yang tidak sesuai dengan paragraf tersebut adalah...",
      options: [
        { id: "A", text: "Pembangunan berkelanjutan memperhatikan kebutuhan generasi mendatang" },
        { id: "B", text: "Pembangunan berkelanjutan mencakup aspek ekonomi, sosial, dan lingkungan" },
        { id: "C", text: "Pembangunan berkelanjutan mengutamakan pertumbuhan ekonomi di atas segalanya" },
        { id: "D", text: "Pembangunan berkelanjutan bertujuan untuk mencapai keseimbangan" },
      ],
      correctAnswer: "C",
      explanation:
        'Pernyataan yang tidak sesuai dengan paragraf tersebut adalah "Pembangunan berkelanjutan mengutamakan pertumbuhan ekonomi di atas segalanya". Paragraf menyatakan bahwa pembangunan berkelanjutan bertujuan untuk mencapai keseimbangan antara pertumbuhan ekonomi, kesejahteraan sosial, dan pelestarian lingkungan, bukan mengutamakan salah satu aspek di atas yang lain.',
    },
    {
      id: 28,
      text: "Bacalah paragraf berikut:\n\nKeanekaragaman budaya Indonesia merupakan kekayaan yang tak ternilai. Setiap suku bangsa memiliki bahasa, adat istiadat, dan kesenian yang unik. Keanekaragaman ini menjadi identitas bangsa Indonesia dan harus dilestarikan. Namun, globalisasi dan modernisasi dapat mengancam kelestarian budaya tradisional jika tidak dikelola dengan baik.\n\nKalimat utama paragraf tersebut adalah...",
      options: [
        { id: "A", text: "Keanekaragaman budaya Indonesia merupakan kekayaan yang tak ternilai." },
        { id: "B", text: "Setiap suku bangsa memiliki bahasa, adat istiadat, dan kesenian yang unik." },
        { id: "C", text: "Keanekaragaman ini menjadi identitas bangsa Indonesia dan harus dilestarikan." },
        {
          id: "D",
          text: "Globalisasi dan modernisasi dapat mengancam kelestarian budaya tradisional jika tidak dikelola dengan baik.",
        },
      ],
      correctAnswer: "A",
      explanation:
        'Kalimat utama paragraf tersebut adalah "Keanekaragaman budaya Indonesia merupakan kekayaan yang tak ternilai." Kalimat ini merupakan kalimat pertama paragraf yang menyatakan ide pokok, dan kalimat-kalimat selanjutnya menjelaskan atau mendukung ide tersebut.',
    },
    {
      id: 29,
      text: "Bacalah paragraf berikut:\n\nPemanfaatan energi terbarukan merupakan salah satu solusi untuk mengatasi krisis energi dan perubahan iklim. Energi terbarukan, seperti energi matahari, angin, dan air, tidak akan habis dan lebih ramah lingkungan dibandingkan dengan bahan bakar fosil. Namun, pengembangan dan pemanfaatan energi terbarukan masih menghadapi berbagai tantangan, seperti biaya yang tinggi dan infrastruktur yang belum memadai.\n\nKesimpulan yang tepat dari paragraf tersebut adalah...",
      options: [
        { id: "A", text: "Energi terbarukan adalah satu-satunya solusi untuk krisis energi" },
        { id: "B", text: "Energi terbarukan memiliki potensi besar tetapi juga tantangan dalam pengembangannya" },
        { id: "C", text: "Biaya tinggi membuat energi terbarukan tidak layak dikembangkan" },
        { id: "D", text: "Bahan bakar fosil masih lebih baik daripada energi terbarukan" },
      ],
      correctAnswer: "B",
      explanation:
        'Kesimpulan yang tepat dari paragraf tersebut adalah "Energi terbarukan memiliki potensi besar tetapi juga tantangan dalam pengembangannya". Paragraf menyatakan bahwa energi terbarukan merupakan solusi untuk krisis energi dan perubahan iklim, tetapi pengembangan dan pemanfaatannya masih menghadapi berbagai tantangan.',
    },
    {
      id: 30,
      text: "Bacalah paragraf berikut:\n\nKesenjangan digital merupakan kesenjangan antara individu, rumah tangga, bisnis, dan area geografis pada tingkat sosial-ekonomi yang berbeda dalam hal akses terhadap teknologi informasi dan komunikasi. Kesenjangan ini dapat memperlebar kesenjangan sosial dan ekonomi yang sudah ada. Oleh karena itu, penting untuk mengatasi kesenjangan digital melalui berbagai kebijakan dan program yang inklusif.\n\nGagasan utama paragraf tersebut adalah...",
      options: [
        { id: "A", text: "Definisi kesenjangan digital" },
        { id: "B", text: "Dampak kesenjangan digital terhadap kesenjangan sosial dan ekonomi" },
        { id: "C", text: "Pentingnya mengatasi kesenjangan digital" },
        { id: "D", text: "Kesenjangan digital dan upaya mengatasinya" },
      ],
      correctAnswer: "D",
      explanation:
        "Gagasan utama paragraf tersebut adalah kesenjangan digital dan upaya mengatasinya. Paragraf dimulai dengan menjelaskan apa itu kesenjangan digital, dampaknya, dan pentingnya mengatasi kesenjangan tersebut.",
    },
  ]
  